// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/clinic_data.proto

package clinicdatapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// COMMON
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_clinic_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{0}
}

// PATIENT
type Patient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	BirthDate     string                 `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Patient) Reset() {
	*x = Patient{}
	mi := &file_proto_clinic_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient) ProtoMessage() {}

func (x *Patient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient.ProtoReflect.Descriptor instead.
func (*Patient) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{1}
}

func (x *Patient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Patient) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Patient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Patient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Patient) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *Patient) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Patient) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Patient) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreatePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	BirthDate     string                 `protobuf:"bytes,3,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePatientRequest) Reset() {
	*x = CreatePatientRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePatientRequest) ProtoMessage() {}

func (x *CreatePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePatientRequest.ProtoReflect.Descriptor instead.
func (*CreatePatientRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePatientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePatientRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreatePatientRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *CreatePatientRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreatePatientRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreatePatientRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UpdatePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	BirthDate     string                 `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatientRequest) Reset() {
	*x = UpdatePatientRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatientRequest) ProtoMessage() {}

func (x *UpdatePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatientRequest.ProtoReflect.Descriptor instead.
func (*UpdatePatientRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePatientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePatientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePatientRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdatePatientRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *UpdatePatientRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdatePatientRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdatePatientRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetPatientByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientByIDRequest) Reset() {
	*x = GetPatientByIDRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientByIDRequest) ProtoMessage() {}

func (x *GetPatientByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientByIDRequest.ProtoReflect.Descriptor instead.
func (*GetPatientByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{4}
}

func (x *GetPatientByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePatientRequest) Reset() {
	*x = DeletePatientRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePatientRequest) ProtoMessage() {}

func (x *DeletePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePatientRequest.ProtoReflect.Descriptor instead.
func (*DeletePatientRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePatientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPatientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*Patient             `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientsResponse) Reset() {
	*x = ListPatientsResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientsResponse) ProtoMessage() {}

func (x *ListPatientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientsResponse.ProtoReflect.Descriptor instead.
func (*ListPatientsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{6}
}

func (x *ListPatientsResponse) GetPatients() []*Patient {
	if x != nil {
		return x.Patients
	}
	return nil
}

type DeletePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePatientResponse) Reset() {
	*x = DeletePatientResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePatientResponse) ProtoMessage() {}

func (x *DeletePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePatientResponse.ProtoReflect.Descriptor instead.
func (*DeletePatientResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePatientResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeletePatientResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeletePatientResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeletePatientResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeletePatientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdatePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatientResponse) Reset() {
	*x = UpdatePatientResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatientResponse) ProtoMessage() {}

func (x *UpdatePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatientResponse.ProtoReflect.Descriptor instead.
func (*UpdatePatientResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePatientResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePatientResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePatientResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePatientResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdatePatientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DOCTOR
type Doctor struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email             string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	SpecializationId  string                 `protobuf:"bytes,5,opt,name=specialization_id,json=specializationId,proto3" json:"specialization_id,omitempty"`
	Age               int32                  `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
	ConsultationFee   float64                `protobuf:"fixed64,7,opt,name=consultation_fee,json=consultationFee,proto3" json:"consultation_fee,omitempty"`
	YearsOfExperience int32                  `protobuf:"varint,8,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	LicenseNumber     string                 `protobuf:"bytes,9,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	PhoneNumber       string                 `protobuf:"bytes,10,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	IsActive          bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Doctor) Reset() {
	*x = Doctor{}
	mi := &file_proto_clinic_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Doctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doctor) ProtoMessage() {}

func (x *Doctor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doctor.ProtoReflect.Descriptor instead.
func (*Doctor) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{9}
}

func (x *Doctor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Doctor) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Doctor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Doctor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Doctor) GetSpecializationId() string {
	if x != nil {
		return x.SpecializationId
	}
	return ""
}

func (x *Doctor) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Doctor) GetConsultationFee() float64 {
	if x != nil {
		return x.ConsultationFee
	}
	return 0
}

func (x *Doctor) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *Doctor) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *Doctor) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Doctor) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateDoctorRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email             string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	SpecializationId  string                 `protobuf:"bytes,3,opt,name=specialization_id,json=specializationId,proto3" json:"specialization_id,omitempty"`
	Age               int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	ConsultationFee   float64                `protobuf:"fixed64,5,opt,name=consultation_fee,json=consultationFee,proto3" json:"consultation_fee,omitempty"`
	YearsOfExperience int32                  `protobuf:"varint,6,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	LicenseNumber     string                 `protobuf:"bytes,7,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	PhoneNumber       string                 `protobuf:"bytes,8,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateDoctorRequest) Reset() {
	*x = CreateDoctorRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDoctorRequest) ProtoMessage() {}

func (x *CreateDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDoctorRequest.ProtoReflect.Descriptor instead.
func (*CreateDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{10}
}

func (x *CreateDoctorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDoctorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateDoctorRequest) GetSpecializationId() string {
	if x != nil {
		return x.SpecializationId
	}
	return ""
}

func (x *CreateDoctorRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateDoctorRequest) GetConsultationFee() float64 {
	if x != nil {
		return x.ConsultationFee
	}
	return 0
}

func (x *CreateDoctorRequest) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *CreateDoctorRequest) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *CreateDoctorRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type UpdateDoctorRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email             string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	SpecializationId  string                 `protobuf:"bytes,4,opt,name=specialization_id,json=specializationId,proto3" json:"specialization_id,omitempty"`
	Age               int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	ConsultationFee   float64                `protobuf:"fixed64,6,opt,name=consultation_fee,json=consultationFee,proto3" json:"consultation_fee,omitempty"`
	YearsOfExperience int32                  `protobuf:"varint,7,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	LicenseNumber     string                 `protobuf:"bytes,8,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	PhoneNumber       string                 `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	IsActive          bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateDoctorRequest) Reset() {
	*x = UpdateDoctorRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDoctorRequest) ProtoMessage() {}

func (x *UpdateDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDoctorRequest.ProtoReflect.Descriptor instead.
func (*UpdateDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateDoctorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDoctorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDoctorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateDoctorRequest) GetSpecializationId() string {
	if x != nil {
		return x.SpecializationId
	}
	return ""
}

func (x *UpdateDoctorRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateDoctorRequest) GetConsultationFee() float64 {
	if x != nil {
		return x.ConsultationFee
	}
	return 0
}

func (x *UpdateDoctorRequest) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *UpdateDoctorRequest) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *UpdateDoctorRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateDoctorRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetDoctorByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorByIDRequest) Reset() {
	*x = GetDoctorByIDRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorByIDRequest) ProtoMessage() {}

func (x *GetDoctorByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{12}
}

func (x *GetDoctorByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDoctorRequest) Reset() {
	*x = DeleteDoctorRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDoctorRequest) ProtoMessage() {}

func (x *DeleteDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDoctorRequest.ProtoReflect.Descriptor instead.
func (*DeleteDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteDoctorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDoctorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doctors       []*Doctor              `protobuf:"bytes,1,rep,name=doctors,proto3" json:"doctors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDoctorsResponse) Reset() {
	*x = ListDoctorsResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDoctorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDoctorsResponse) ProtoMessage() {}

func (x *ListDoctorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDoctorsResponse.ProtoReflect.Descriptor instead.
func (*ListDoctorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{14}
}

func (x *ListDoctorsResponse) GetDoctors() []*Doctor {
	if x != nil {
		return x.Doctors
	}
	return nil
}

type UpdateDoctorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDoctorResponse) Reset() {
	*x = UpdateDoctorResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDoctorResponse) ProtoMessage() {}

func (x *UpdateDoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDoctorResponse.ProtoReflect.Descriptor instead.
func (*UpdateDoctorResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateDoctorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDoctorResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateDoctorResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDoctorResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateDoctorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteDoctorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDoctorResponse) Reset() {
	*x = DeleteDoctorResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDoctorResponse) ProtoMessage() {}

func (x *DeleteDoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDoctorResponse.ProtoReflect.Descriptor instead.
func (*DeleteDoctorResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteDoctorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteDoctorResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteDoctorResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteDoctorResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeleteDoctorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SPECIALIZATION
type Specialization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Specialization) Reset() {
	*x = Specialization{}
	mi := &file_proto_clinic_data_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Specialization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specialization) ProtoMessage() {}

func (x *Specialization) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specialization.ProtoReflect.Descriptor instead.
func (*Specialization) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{17}
}

func (x *Specialization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Specialization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSpecializationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpecializationRequest) Reset() {
	*x = CreateSpecializationRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpecializationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpecializationRequest) ProtoMessage() {}

func (x *CreateSpecializationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpecializationRequest.ProtoReflect.Descriptor instead.
func (*CreateSpecializationRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{18}
}

func (x *CreateSpecializationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateSpecializationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpecializationRequest) Reset() {
	*x = UpdateSpecializationRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpecializationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpecializationRequest) ProtoMessage() {}

func (x *UpdateSpecializationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpecializationRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpecializationRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateSpecializationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSpecializationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSpecializationByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpecializationByIDRequest) Reset() {
	*x = GetSpecializationByIDRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpecializationByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpecializationByIDRequest) ProtoMessage() {}

func (x *GetSpecializationByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpecializationByIDRequest.ProtoReflect.Descriptor instead.
func (*GetSpecializationByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{20}
}

func (x *GetSpecializationByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSpecializationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSpecializationRequest) Reset() {
	*x = DeleteSpecializationRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSpecializationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSpecializationRequest) ProtoMessage() {}

func (x *DeleteSpecializationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSpecializationRequest.ProtoReflect.Descriptor instead.
func (*DeleteSpecializationRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteSpecializationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateSpecializationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpecializationResponse) Reset() {
	*x = UpdateSpecializationResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpecializationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpecializationResponse) ProtoMessage() {}

func (x *UpdateSpecializationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpecializationResponse.ProtoReflect.Descriptor instead.
func (*UpdateSpecializationResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateSpecializationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSpecializationResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSpecializationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteSpecializationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSpecializationResponse) Reset() {
	*x = DeleteSpecializationResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSpecializationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSpecializationResponse) ProtoMessage() {}

func (x *DeleteSpecializationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSpecializationResponse.ProtoReflect.Descriptor instead.
func (*DeleteSpecializationResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteSpecializationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteSpecializationResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteSpecializationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListSpecializationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Specializations []*Specialization      `protobuf:"bytes,1,rep,name=specializations,proto3" json:"specializations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListSpecializationsResponse) Reset() {
	*x = ListSpecializationsResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpecializationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpecializationsResponse) ProtoMessage() {}

func (x *ListSpecializationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpecializationsResponse.ProtoReflect.Descriptor instead.
func (*ListSpecializationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{24}
}

func (x *ListSpecializationsResponse) GetSpecializations() []*Specialization {
	if x != nil {
		return x.Specializations
	}
	return nil
}

// ROOM
type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_proto_clinic_data_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{25}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{26}
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRoomByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomByIDRequest) Reset() {
	*x = GetRoomByIDRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomByIDRequest) ProtoMessage() {}

func (x *GetRoomByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomByIDRequest.ProtoReflect.Descriptor instead.
func (*GetRoomByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{27}
}

func (x *GetRoomByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{28}
}

func (x *ListRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// SCHEDULE FIXED
type ScheduleFixed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,4,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	StartTime     string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleFixed) Reset() {
	*x = ScheduleFixed{}
	mi := &file_proto_clinic_data_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleFixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleFixed) ProtoMessage() {}

func (x *ScheduleFixed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleFixed.ProtoReflect.Descriptor instead.
func (*ScheduleFixed) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{29}
}

func (x *ScheduleFixed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduleFixed) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *ScheduleFixed) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ScheduleFixed) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *ScheduleFixed) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ScheduleFixed) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ScheduleFixed) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateScheduleFixedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      string                 `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,3,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleFixedRequest) Reset() {
	*x = CreateScheduleFixedRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleFixedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleFixedRequest) ProtoMessage() {}

func (x *CreateScheduleFixedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleFixedRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleFixedRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{30}
}

func (x *CreateScheduleFixedRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *CreateScheduleFixedRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateScheduleFixedRequest) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *CreateScheduleFixedRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateScheduleFixedRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateScheduleFixedRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateScheduleFixedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,3,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduleFixedRequest) Reset() {
	*x = UpdateScheduleFixedRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduleFixedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduleFixedRequest) ProtoMessage() {}

func (x *UpdateScheduleFixedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduleFixedRequest.ProtoReflect.Descriptor instead.
func (*UpdateScheduleFixedRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateScheduleFixedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateScheduleFixedRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdateScheduleFixedRequest) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *UpdateScheduleFixedRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdateScheduleFixedRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpdateScheduleFixedRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetFixedSchedulesByDoctorIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      string                 `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFixedSchedulesByDoctorIDRequest) Reset() {
	*x = GetFixedSchedulesByDoctorIDRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFixedSchedulesByDoctorIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFixedSchedulesByDoctorIDRequest) ProtoMessage() {}

func (x *GetFixedSchedulesByDoctorIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFixedSchedulesByDoctorIDRequest.ProtoReflect.Descriptor instead.
func (*GetFixedSchedulesByDoctorIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{32}
}

func (x *GetFixedSchedulesByDoctorIDRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type ListScheduleFixedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*ScheduleFixed       `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduleFixedResponse) Reset() {
	*x = ListScheduleFixedResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduleFixedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduleFixedResponse) ProtoMessage() {}

func (x *ListScheduleFixedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduleFixedResponse.ProtoReflect.Descriptor instead.
func (*ListScheduleFixedResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{33}
}

func (x *ListScheduleFixedResponse) GetSchedules() []*ScheduleFixed {
	if x != nil {
		return x.Schedules
	}
	return nil
}

// SCHEDULE OVERRIDE
type ScheduleOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,4,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	StartTime     string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleOverride) Reset() {
	*x = ScheduleOverride{}
	mi := &file_proto_clinic_data_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleOverride) ProtoMessage() {}

func (x *ScheduleOverride) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleOverride.ProtoReflect.Descriptor instead.
func (*ScheduleOverride) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{34}
}

func (x *ScheduleOverride) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduleOverride) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *ScheduleOverride) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ScheduleOverride) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *ScheduleOverride) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ScheduleOverride) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ScheduleOverride) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateScheduleOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      string                 `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,3,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleOverrideRequest) Reset() {
	*x = CreateScheduleOverrideRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleOverrideRequest) ProtoMessage() {}

func (x *CreateScheduleOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleOverrideRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{35}
}

func (x *CreateScheduleOverrideRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *CreateScheduleOverrideRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateScheduleOverrideRequest) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *CreateScheduleOverrideRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateScheduleOverrideRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateScheduleOverrideRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateScheduleOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduleOverrideRequest) Reset() {
	*x = UpdateScheduleOverrideRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduleOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduleOverrideRequest) ProtoMessage() {}

func (x *UpdateScheduleOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduleOverrideRequest.ProtoReflect.Descriptor instead.
func (*UpdateScheduleOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{36}
}

func (x *UpdateScheduleOverrideRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateScheduleOverrideRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdateScheduleOverrideRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdateScheduleOverrideRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpdateScheduleOverrideRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteScheduleOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleOverrideRequest) Reset() {
	*x = DeleteScheduleOverrideRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleOverrideRequest) ProtoMessage() {}

func (x *DeleteScheduleOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleOverrideRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduleOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{37}
}

func (x *DeleteScheduleOverrideRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOverrideByDoctorIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      string                 `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverrideByDoctorIDRequest) Reset() {
	*x = GetOverrideByDoctorIDRequest{}
	mi := &file_proto_clinic_data_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverrideByDoctorIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverrideByDoctorIDRequest) ProtoMessage() {}

func (x *GetOverrideByDoctorIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverrideByDoctorIDRequest.ProtoReflect.Descriptor instead.
func (*GetOverrideByDoctorIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{38}
}

func (x *GetOverrideByDoctorIDRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type ListScheduleOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overrides     []*ScheduleOverride    `protobuf:"bytes,1,rep,name=overrides,proto3" json:"overrides,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduleOverrideResponse) Reset() {
	*x = ListScheduleOverrideResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduleOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduleOverrideResponse) ProtoMessage() {}

func (x *ListScheduleOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduleOverrideResponse.ProtoReflect.Descriptor instead.
func (*ListScheduleOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{39}
}

func (x *ListScheduleOverrideResponse) GetOverrides() []*ScheduleOverride {
	if x != nil {
		return x.Overrides
	}
	return nil
}

type UpdateScheduleOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,3,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduleOverrideResponse) Reset() {
	*x = UpdateScheduleOverrideResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduleOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduleOverrideResponse) ProtoMessage() {}

func (x *UpdateScheduleOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduleOverrideResponse.ProtoReflect.Descriptor instead.
func (*UpdateScheduleOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{40}
}

func (x *UpdateScheduleOverrideResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateScheduleOverrideResponse) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *UpdateScheduleOverrideResponse) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *UpdateScheduleOverrideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteScheduleOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,3,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleOverrideResponse) Reset() {
	*x = DeleteScheduleOverrideResponse{}
	mi := &file_proto_clinic_data_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleOverrideResponse) ProtoMessage() {}

func (x *DeleteScheduleOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clinic_data_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleOverrideResponse.ProtoReflect.Descriptor instead.
func (*DeleteScheduleOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_clinic_data_proto_rawDescGZIP(), []int{41}
}

func (x *DeleteScheduleOverrideResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteScheduleOverrideResponse) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *DeleteScheduleOverrideResponse) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *DeleteScheduleOverrideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_clinic_data_proto protoreflect.FileDescriptor

const file_proto_clinic_data_proto_rawDesc = "" +
	"\n" +
	"\x17proto/clinic_data.proto\x12\n" +
	"clinicdata\"\a\n" +
	"\x05Empty\"\xd0\x01\n" +
	"\aPatient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\"\xb4\x01\n" +
	"\x14CreatePatientRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x03 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\"\xc4\x01\n" +
	"\x14UpdatePatientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\"'\n" +
	"\x15GetPatientByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14DeletePatientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x14ListPatientsResponse\x12/\n" +
	"\bpatients\x18\x01 \x03(\v2\x13.clinicdata.PatientR\bpatients\"\x84\x01\n" +
	"\x15DeletePatientResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x84\x01\n" +
	"\x15UpdatePatientResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xdc\x02\n" +
	"\x06Doctor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12+\n" +
	"\x11specialization_id\x18\x05 \x01(\tR\x10specializationId\x12\x10\n" +
	"\x03age\x18\x06 \x01(\x05R\x03age\x12)\n" +
	"\x10consultation_fee\x18\a \x01(\x01R\x0fconsultationFee\x12.\n" +
	"\x13years_of_experience\x18\b \x01(\x05R\x11yearsOfExperience\x12%\n" +
	"\x0elicense_number\x18\t \x01(\tR\rlicenseNumber\x12!\n" +
	"\fphone_number\x18\n" +
	" \x01(\tR\vphoneNumber\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\"\xa3\x02\n" +
	"\x13CreateDoctorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12+\n" +
	"\x11specialization_id\x18\x03 \x01(\tR\x10specializationId\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12)\n" +
	"\x10consultation_fee\x18\x05 \x01(\x01R\x0fconsultationFee\x12.\n" +
	"\x13years_of_experience\x18\x06 \x01(\x05R\x11yearsOfExperience\x12%\n" +
	"\x0elicense_number\x18\a \x01(\tR\rlicenseNumber\x12!\n" +
	"\fphone_number\x18\b \x01(\tR\vphoneNumber\"\xd0\x02\n" +
	"\x13UpdateDoctorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12+\n" +
	"\x11specialization_id\x18\x04 \x01(\tR\x10specializationId\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\x12)\n" +
	"\x10consultation_fee\x18\x06 \x01(\x01R\x0fconsultationFee\x12.\n" +
	"\x13years_of_experience\x18\a \x01(\x05R\x11yearsOfExperience\x12%\n" +
	"\x0elicense_number\x18\b \x01(\tR\rlicenseNumber\x12!\n" +
	"\fphone_number\x18\t \x01(\tR\vphoneNumber\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\"&\n" +
	"\x14GetDoctorByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13DeleteDoctorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x13ListDoctorsResponse\x12,\n" +
	"\adoctors\x18\x01 \x03(\v2\x12.clinicdata.DoctorR\adoctors\"\x83\x01\n" +
	"\x14UpdateDoctorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x83\x01\n" +
	"\x14DeleteDoctorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"4\n" +
	"\x0eSpecialization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"1\n" +
	"\x1bCreateSpecializationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"A\n" +
	"\x1bUpdateSpecializationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\".\n" +
	"\x1cGetSpecializationByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x1bDeleteSpecializationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x1cUpdateSpecializationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\\\n" +
	"\x1cDeleteSpecializationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"c\n" +
	"\x1bListSpecializationsResponse\x12D\n" +
	"\x0fspecializations\x18\x01 \x03(\v2\x1a.clinicdata.SpecializationR\x0fspecializations\"G\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\"'\n" +
	"\x11CreateRoomRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"$\n" +
	"\x12GetRoomByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x11ListRoomsResponse\x12&\n" +
	"\x05rooms\x18\x01 \x03(\v2\x10.clinicdata.RoomR\x05rooms\"\xc7\x01\n" +
	"\rScheduleFixed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\tR\bdoctorId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1e\n" +
	"\vday_of_week\x18\x04 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xc4\x01\n" +
	"\x1aCreateScheduleFixedRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\tR\bdoctorId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1e\n" +
	"\vday_of_week\x18\x03 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xb7\x01\n" +
	"\x1aUpdateScheduleFixedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1e\n" +
	"\vday_of_week\x18\x03 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"A\n" +
	"\"GetFixedSchedulesByDoctorIDRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\tR\bdoctorId\"T\n" +
	"\x19ListScheduleFixedResponse\x127\n" +
	"\tschedules\x18\x01 \x03(\v2\x19.clinicdata.ScheduleFixedR\tschedules\"\xca\x01\n" +
	"\x10ScheduleOverride\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\tR\bdoctorId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1e\n" +
	"\vday_of_week\x18\x04 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xc7\x01\n" +
	"\x1dCreateScheduleOverrideRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\tR\bdoctorId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1e\n" +
	"\vday_of_week\x18\x03 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x9a\x01\n" +
	"\x1dUpdateScheduleOverrideRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"/\n" +
	"\x1dDeleteScheduleOverrideRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x1cGetOverrideByDoctorIDRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\tR\bdoctorId\"Z\n" +
	"\x1cListScheduleOverrideResponse\x12:\n" +
	"\toverrides\x18\x01 \x03(\v2\x1c.clinicdata.ScheduleOverrideR\toverrides\"\x87\x01\n" +
	"\x1eUpdateScheduleOverrideResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\tR\bdoctorId\x12\x1e\n" +
	"\vday_of_week\x18\x03 \x01(\x05R\tdayOfWeek\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x87\x01\n" +
	"\x1eDeleteScheduleOverrideResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\tR\bdoctorId\x12\x1e\n" +
	"\vday_of_week\x18\x03 \x01(\x05R\tdayOfWeek\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\x93\x11\n" +
	"\x11ClinicDataService\x12F\n" +
	"\rCreatePatient\x12 .clinicdata.CreatePatientRequest\x1a\x13.clinicdata.Patient\x12H\n" +
	"\x0eGetPatientByID\x12!.clinicdata.GetPatientByIDRequest\x1a\x13.clinicdata.Patient\x12E\n" +
	"\x0eGetAllPatients\x12\x11.clinicdata.Empty\x1a .clinicdata.ListPatientsResponse\x12T\n" +
	"\rUpdatePatient\x12 .clinicdata.UpdatePatientRequest\x1a!.clinicdata.UpdatePatientResponse\x12T\n" +
	"\rDeletePatient\x12 .clinicdata.DeletePatientRequest\x1a!.clinicdata.DeletePatientResponse\x12C\n" +
	"\fCreateDoctor\x12\x1f.clinicdata.CreateDoctorRequest\x1a\x12.clinicdata.Doctor\x12E\n" +
	"\rGetDoctorByID\x12 .clinicdata.GetDoctorByIDRequest\x1a\x12.clinicdata.Doctor\x12C\n" +
	"\rGetAllDoctors\x12\x11.clinicdata.Empty\x1a\x1f.clinicdata.ListDoctorsResponse\x12Q\n" +
	"\fUpdateDoctor\x12\x1f.clinicdata.UpdateDoctorRequest\x1a .clinicdata.UpdateDoctorResponse\x12Q\n" +
	"\fDeleteDoctor\x12\x1f.clinicdata.DeleteDoctorRequest\x1a .clinicdata.DeleteDoctorResponse\x12[\n" +
	"\x14CreateSpecialization\x12'.clinicdata.CreateSpecializationRequest\x1a\x1a.clinicdata.Specialization\x12]\n" +
	"\x15GetSpecializationByID\x12(.clinicdata.GetSpecializationByIDRequest\x1a\x1a.clinicdata.Specialization\x12S\n" +
	"\x15GetAllSpecializations\x12\x11.clinicdata.Empty\x1a'.clinicdata.ListSpecializationsResponse\x12i\n" +
	"\x14UpdateSpecialization\x12'.clinicdata.UpdateSpecializationRequest\x1a(.clinicdata.UpdateSpecializationResponse\x12i\n" +
	"\x14DeleteSpecialization\x12'.clinicdata.DeleteSpecializationRequest\x1a(.clinicdata.DeleteSpecializationResponse\x12=\n" +
	"\n" +
	"CreateRoom\x12\x1d.clinicdata.CreateRoomRequest\x1a\x10.clinicdata.Room\x12?\n" +
	"\vGetRoomByID\x12\x1e.clinicdata.GetRoomByIDRequest\x1a\x10.clinicdata.Room\x12?\n" +
	"\vGetAllRooms\x12\x11.clinicdata.Empty\x1a\x1d.clinicdata.ListRoomsResponse\x12X\n" +
	"\x13CreateScheduleFixed\x12&.clinicdata.CreateScheduleFixedRequest\x1a\x19.clinicdata.ScheduleFixed\x12t\n" +
	"\x1bGetFixedSchedulesByDoctorID\x12..clinicdata.GetFixedSchedulesByDoctorIDRequest\x1a%.clinicdata.ListScheduleFixedResponse\x12X\n" +
	"\x13UpdateScheduleFixed\x12&.clinicdata.UpdateScheduleFixedRequest\x1a\x19.clinicdata.ScheduleFixed\x12a\n" +
	"\x16CreateScheduleOverride\x12).clinicdata.CreateScheduleOverrideRequest\x1a\x1c.clinicdata.ScheduleOverride\x12k\n" +
	"\x15GetOverrideByDoctorID\x12(.clinicdata.GetOverrideByDoctorIDRequest\x1a(.clinicdata.ListScheduleOverrideResponse\x12o\n" +
	"\x16UpdateScheduleOverride\x12).clinicdata.UpdateScheduleOverrideRequest\x1a*.clinicdata.UpdateScheduleOverrideResponse\x12o\n" +
	"\x16DeleteScheduleOverride\x12).clinicdata.DeleteScheduleOverrideRequest\x1a*.clinicdata.DeleteScheduleOverrideResponseB0Z.internal/clinicdata/delivery/grpc/clinicdatapbb\x06proto3"

var (
	file_proto_clinic_data_proto_rawDescOnce sync.Once
	file_proto_clinic_data_proto_rawDescData []byte
)

func file_proto_clinic_data_proto_rawDescGZIP() []byte {
	file_proto_clinic_data_proto_rawDescOnce.Do(func() {
		file_proto_clinic_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clinic_data_proto_rawDesc), len(file_proto_clinic_data_proto_rawDesc)))
	})
	return file_proto_clinic_data_proto_rawDescData
}

var file_proto_clinic_data_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_proto_clinic_data_proto_goTypes = []any{
	(*Empty)(nil),                              // 0: clinicdata.Empty
	(*Patient)(nil),                            // 1: clinicdata.Patient
	(*CreatePatientRequest)(nil),               // 2: clinicdata.CreatePatientRequest
	(*UpdatePatientRequest)(nil),               // 3: clinicdata.UpdatePatientRequest
	(*GetPatientByIDRequest)(nil),              // 4: clinicdata.GetPatientByIDRequest
	(*DeletePatientRequest)(nil),               // 5: clinicdata.DeletePatientRequest
	(*ListPatientsResponse)(nil),               // 6: clinicdata.ListPatientsResponse
	(*DeletePatientResponse)(nil),              // 7: clinicdata.DeletePatientResponse
	(*UpdatePatientResponse)(nil),              // 8: clinicdata.UpdatePatientResponse
	(*Doctor)(nil),                             // 9: clinicdata.Doctor
	(*CreateDoctorRequest)(nil),                // 10: clinicdata.CreateDoctorRequest
	(*UpdateDoctorRequest)(nil),                // 11: clinicdata.UpdateDoctorRequest
	(*GetDoctorByIDRequest)(nil),               // 12: clinicdata.GetDoctorByIDRequest
	(*DeleteDoctorRequest)(nil),                // 13: clinicdata.DeleteDoctorRequest
	(*ListDoctorsResponse)(nil),                // 14: clinicdata.ListDoctorsResponse
	(*UpdateDoctorResponse)(nil),               // 15: clinicdata.UpdateDoctorResponse
	(*DeleteDoctorResponse)(nil),               // 16: clinicdata.DeleteDoctorResponse
	(*Specialization)(nil),                     // 17: clinicdata.Specialization
	(*CreateSpecializationRequest)(nil),        // 18: clinicdata.CreateSpecializationRequest
	(*UpdateSpecializationRequest)(nil),        // 19: clinicdata.UpdateSpecializationRequest
	(*GetSpecializationByIDRequest)(nil),       // 20: clinicdata.GetSpecializationByIDRequest
	(*DeleteSpecializationRequest)(nil),        // 21: clinicdata.DeleteSpecializationRequest
	(*UpdateSpecializationResponse)(nil),       // 22: clinicdata.UpdateSpecializationResponse
	(*DeleteSpecializationResponse)(nil),       // 23: clinicdata.DeleteSpecializationResponse
	(*ListSpecializationsResponse)(nil),        // 24: clinicdata.ListSpecializationsResponse
	(*Room)(nil),                               // 25: clinicdata.Room
	(*CreateRoomRequest)(nil),                  // 26: clinicdata.CreateRoomRequest
	(*GetRoomByIDRequest)(nil),                 // 27: clinicdata.GetRoomByIDRequest
	(*ListRoomsResponse)(nil),                  // 28: clinicdata.ListRoomsResponse
	(*ScheduleFixed)(nil),                      // 29: clinicdata.ScheduleFixed
	(*CreateScheduleFixedRequest)(nil),         // 30: clinicdata.CreateScheduleFixedRequest
	(*UpdateScheduleFixedRequest)(nil),         // 31: clinicdata.UpdateScheduleFixedRequest
	(*GetFixedSchedulesByDoctorIDRequest)(nil), // 32: clinicdata.GetFixedSchedulesByDoctorIDRequest
	(*ListScheduleFixedResponse)(nil),          // 33: clinicdata.ListScheduleFixedResponse
	(*ScheduleOverride)(nil),                   // 34: clinicdata.ScheduleOverride
	(*CreateScheduleOverrideRequest)(nil),      // 35: clinicdata.CreateScheduleOverrideRequest
	(*UpdateScheduleOverrideRequest)(nil),      // 36: clinicdata.UpdateScheduleOverrideRequest
	(*DeleteScheduleOverrideRequest)(nil),      // 37: clinicdata.DeleteScheduleOverrideRequest
	(*GetOverrideByDoctorIDRequest)(nil),       // 38: clinicdata.GetOverrideByDoctorIDRequest
	(*ListScheduleOverrideResponse)(nil),       // 39: clinicdata.ListScheduleOverrideResponse
	(*UpdateScheduleOverrideResponse)(nil),     // 40: clinicdata.UpdateScheduleOverrideResponse
	(*DeleteScheduleOverrideResponse)(nil),     // 41: clinicdata.DeleteScheduleOverrideResponse
}
var file_proto_clinic_data_proto_depIdxs = []int32{
	1,  // 0: clinicdata.ListPatientsResponse.patients:type_name -> clinicdata.Patient
	9,  // 1: clinicdata.ListDoctorsResponse.doctors:type_name -> clinicdata.Doctor
	17, // 2: clinicdata.ListSpecializationsResponse.specializations:type_name -> clinicdata.Specialization
	25, // 3: clinicdata.ListRoomsResponse.rooms:type_name -> clinicdata.Room
	29, // 4: clinicdata.ListScheduleFixedResponse.schedules:type_name -> clinicdata.ScheduleFixed
	34, // 5: clinicdata.ListScheduleOverrideResponse.overrides:type_name -> clinicdata.ScheduleOverride
	2,  // 6: clinicdata.ClinicDataService.CreatePatient:input_type -> clinicdata.CreatePatientRequest
	4,  // 7: clinicdata.ClinicDataService.GetPatientByID:input_type -> clinicdata.GetPatientByIDRequest
	0,  // 8: clinicdata.ClinicDataService.GetAllPatients:input_type -> clinicdata.Empty
	3,  // 9: clinicdata.ClinicDataService.UpdatePatient:input_type -> clinicdata.UpdatePatientRequest
	5,  // 10: clinicdata.ClinicDataService.DeletePatient:input_type -> clinicdata.DeletePatientRequest
	10, // 11: clinicdata.ClinicDataService.CreateDoctor:input_type -> clinicdata.CreateDoctorRequest
	12, // 12: clinicdata.ClinicDataService.GetDoctorByID:input_type -> clinicdata.GetDoctorByIDRequest
	0,  // 13: clinicdata.ClinicDataService.GetAllDoctors:input_type -> clinicdata.Empty
	11, // 14: clinicdata.ClinicDataService.UpdateDoctor:input_type -> clinicdata.UpdateDoctorRequest
	13, // 15: clinicdata.ClinicDataService.DeleteDoctor:input_type -> clinicdata.DeleteDoctorRequest
	18, // 16: clinicdata.ClinicDataService.CreateSpecialization:input_type -> clinicdata.CreateSpecializationRequest
	20, // 17: clinicdata.ClinicDataService.GetSpecializationByID:input_type -> clinicdata.GetSpecializationByIDRequest
	0,  // 18: clinicdata.ClinicDataService.GetAllSpecializations:input_type -> clinicdata.Empty
	19, // 19: clinicdata.ClinicDataService.UpdateSpecialization:input_type -> clinicdata.UpdateSpecializationRequest
	21, // 20: clinicdata.ClinicDataService.DeleteSpecialization:input_type -> clinicdata.DeleteSpecializationRequest
	26, // 21: clinicdata.ClinicDataService.CreateRoom:input_type -> clinicdata.CreateRoomRequest
	27, // 22: clinicdata.ClinicDataService.GetRoomByID:input_type -> clinicdata.GetRoomByIDRequest
	0,  // 23: clinicdata.ClinicDataService.GetAllRooms:input_type -> clinicdata.Empty
	30, // 24: clinicdata.ClinicDataService.CreateScheduleFixed:input_type -> clinicdata.CreateScheduleFixedRequest
	32, // 25: clinicdata.ClinicDataService.GetFixedSchedulesByDoctorID:input_type -> clinicdata.GetFixedSchedulesByDoctorIDRequest
	31, // 26: clinicdata.ClinicDataService.UpdateScheduleFixed:input_type -> clinicdata.UpdateScheduleFixedRequest
	35, // 27: clinicdata.ClinicDataService.CreateScheduleOverride:input_type -> clinicdata.CreateScheduleOverrideRequest
	38, // 28: clinicdata.ClinicDataService.GetOverrideByDoctorID:input_type -> clinicdata.GetOverrideByDoctorIDRequest
	36, // 29: clinicdata.ClinicDataService.UpdateScheduleOverride:input_type -> clinicdata.UpdateScheduleOverrideRequest
	37, // 30: clinicdata.ClinicDataService.DeleteScheduleOverride:input_type -> clinicdata.DeleteScheduleOverrideRequest
	1,  // 31: clinicdata.ClinicDataService.CreatePatient:output_type -> clinicdata.Patient
	1,  // 32: clinicdata.ClinicDataService.GetPatientByID:output_type -> clinicdata.Patient
	6,  // 33: clinicdata.ClinicDataService.GetAllPatients:output_type -> clinicdata.ListPatientsResponse
	8,  // 34: clinicdata.ClinicDataService.UpdatePatient:output_type -> clinicdata.UpdatePatientResponse
	7,  // 35: clinicdata.ClinicDataService.DeletePatient:output_type -> clinicdata.DeletePatientResponse
	9,  // 36: clinicdata.ClinicDataService.CreateDoctor:output_type -> clinicdata.Doctor
	9,  // 37: clinicdata.ClinicDataService.GetDoctorByID:output_type -> clinicdata.Doctor
	14, // 38: clinicdata.ClinicDataService.GetAllDoctors:output_type -> clinicdata.ListDoctorsResponse
	15, // 39: clinicdata.ClinicDataService.UpdateDoctor:output_type -> clinicdata.UpdateDoctorResponse
	16, // 40: clinicdata.ClinicDataService.DeleteDoctor:output_type -> clinicdata.DeleteDoctorResponse
	17, // 41: clinicdata.ClinicDataService.CreateSpecialization:output_type -> clinicdata.Specialization
	17, // 42: clinicdata.ClinicDataService.GetSpecializationByID:output_type -> clinicdata.Specialization
	24, // 43: clinicdata.ClinicDataService.GetAllSpecializations:output_type -> clinicdata.ListSpecializationsResponse
	22, // 44: clinicdata.ClinicDataService.UpdateSpecialization:output_type -> clinicdata.UpdateSpecializationResponse
	23, // 45: clinicdata.ClinicDataService.DeleteSpecialization:output_type -> clinicdata.DeleteSpecializationResponse
	25, // 46: clinicdata.ClinicDataService.CreateRoom:output_type -> clinicdata.Room
	25, // 47: clinicdata.ClinicDataService.GetRoomByID:output_type -> clinicdata.Room
	28, // 48: clinicdata.ClinicDataService.GetAllRooms:output_type -> clinicdata.ListRoomsResponse
	29, // 49: clinicdata.ClinicDataService.CreateScheduleFixed:output_type -> clinicdata.ScheduleFixed
	33, // 50: clinicdata.ClinicDataService.GetFixedSchedulesByDoctorID:output_type -> clinicdata.ListScheduleFixedResponse
	29, // 51: clinicdata.ClinicDataService.UpdateScheduleFixed:output_type -> clinicdata.ScheduleFixed
	34, // 52: clinicdata.ClinicDataService.CreateScheduleOverride:output_type -> clinicdata.ScheduleOverride
	39, // 53: clinicdata.ClinicDataService.GetOverrideByDoctorID:output_type -> clinicdata.ListScheduleOverrideResponse
	40, // 54: clinicdata.ClinicDataService.UpdateScheduleOverride:output_type -> clinicdata.UpdateScheduleOverrideResponse
	41, // 55: clinicdata.ClinicDataService.DeleteScheduleOverride:output_type -> clinicdata.DeleteScheduleOverrideResponse
	31, // [31:56] is the sub-list for method output_type
	6,  // [6:31] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_clinic_data_proto_init() }
func file_proto_clinic_data_proto_init() {
	if File_proto_clinic_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clinic_data_proto_rawDesc), len(file_proto_clinic_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clinic_data_proto_goTypes,
		DependencyIndexes: file_proto_clinic_data_proto_depIdxs,
		MessageInfos:      file_proto_clinic_data_proto_msgTypes,
	}.Build()
	File_proto_clinic_data_proto = out.File
	file_proto_clinic_data_proto_goTypes = nil
	file_proto_clinic_data_proto_depIdxs = nil
}
