// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: queue.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Queue struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserRole             string                 `protobuf:"bytes,4,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	PatientId            *uint32                `protobuf:"varint,5,opt,name=patient_id,json=patientId,proto3,oneof" json:"patient_id,omitempty"`
	PatientName          *string                `protobuf:"bytes,6,opt,name=patient_name,json=patientName,proto3,oneof" json:"patient_name,omitempty"`
	DoctorId             uint32                 `protobuf:"varint,7,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DoctorName           string                 `protobuf:"bytes,8,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`
	DoctorSpecialization string                 `protobuf:"bytes,9,opt,name=doctor_specialization,json=doctorSpecialization,proto3" json:"doctor_specialization,omitempty"`
	AppointmentId        *uint32                `protobuf:"varint,10,opt,name=appointment_id,json=appointmentId,proto3,oneof" json:"appointment_id,omitempty"`
	Type                 string                 `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	QueueNumber          int32                  `protobuf:"varint,12,opt,name=queue_number,json=queueNumber,proto3" json:"queue_number,omitempty"`
	StartFrom            string                 `protobuf:"bytes,13,opt,name=start_from,json=startFrom,proto3" json:"start_from,omitempty"`
	Status               string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{0}
}

func (x *Queue) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Queue) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Queue) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Queue) GetUserRole() string {
	if x != nil {
		return x.UserRole
	}
	return ""
}

func (x *Queue) GetPatientId() uint32 {
	if x != nil && x.PatientId != nil {
		return *x.PatientId
	}
	return 0
}

func (x *Queue) GetPatientName() string {
	if x != nil && x.PatientName != nil {
		return *x.PatientName
	}
	return ""
}

func (x *Queue) GetDoctorId() uint32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *Queue) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *Queue) GetDoctorSpecialization() string {
	if x != nil {
		return x.DoctorSpecialization
	}
	return ""
}

func (x *Queue) GetAppointmentId() uint32 {
	if x != nil && x.AppointmentId != nil {
		return *x.AppointmentId
	}
	return 0
}

func (x *Queue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Queue) GetQueueNumber() int32 {
	if x != nil {
		return x.QueueNumber
	}
	return 0
}

func (x *Queue) GetStartFrom() string {
	if x != nil {
		return x.StartFrom
	}
	return ""
}

func (x *Queue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Queue) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type QueueIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueIDRequest) Reset() {
	*x = QueueIDRequest{}
	mi := &file_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueIDRequest) ProtoMessage() {}

func (x *QueueIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueIDRequest.ProtoReflect.Descriptor instead.
func (*QueueIDRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{1}
}

func (x *QueueIDRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DoctorIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      uint32                 `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorIDRequest) Reset() {
	*x = DoctorIDRequest{}
	mi := &file_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorIDRequest) ProtoMessage() {}

func (x *DoctorIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorIDRequest.ProtoReflect.Descriptor instead.
func (*DoctorIDRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{2}
}

func (x *DoctorIDRequest) GetDoctorId() uint32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

type CreateQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *Queue                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueRequest) Reset() {
	*x = CreateQueueRequest{}
	mi := &file_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueRequest) ProtoMessage() {}

func (x *CreateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueRequest.ProtoReflect.Descriptor instead.
func (*CreateQueueRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{3}
}

func (x *CreateQueueRequest) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

type UpdateQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *Queue                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQueueRequest) Reset() {
	*x = UpdateQueueRequest{}
	mi := &file_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQueueRequest) ProtoMessage() {}

func (x *UpdateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQueueRequest.ProtoReflect.Descriptor instead.
func (*UpdateQueueRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateQueueRequest) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

type GenerateQueueRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DoctorId             uint32                 `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	UserId               uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserRole             string                 `protobuf:"bytes,4,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	AppointmentId        *uint32                `protobuf:"varint,5,opt,name=appointment_id,json=appointmentId,proto3,oneof" json:"appointment_id,omitempty"`
	PatientId            *uint32                `protobuf:"varint,6,opt,name=patient_id,json=patientId,proto3,oneof" json:"patient_id,omitempty"`
	PatientName          *string                `protobuf:"bytes,7,opt,name=patient_name,json=patientName,proto3,oneof" json:"patient_name,omitempty"`
	DoctorName           string                 `protobuf:"bytes,8,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`
	DoctorSpecialization string                 `protobuf:"bytes,9,opt,name=doctor_specialization,json=doctorSpecialization,proto3" json:"doctor_specialization,omitempty"`
	Type                 string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GenerateQueueRequest) Reset() {
	*x = GenerateQueueRequest{}
	mi := &file_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQueueRequest) ProtoMessage() {}

func (x *GenerateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQueueRequest.ProtoReflect.Descriptor instead.
func (*GenerateQueueRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateQueueRequest) GetDoctorId() uint32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *GenerateQueueRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GenerateQueueRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GenerateQueueRequest) GetUserRole() string {
	if x != nil {
		return x.UserRole
	}
	return ""
}

func (x *GenerateQueueRequest) GetAppointmentId() uint32 {
	if x != nil && x.AppointmentId != nil {
		return *x.AppointmentId
	}
	return 0
}

func (x *GenerateQueueRequest) GetPatientId() uint32 {
	if x != nil && x.PatientId != nil {
		return *x.PatientId
	}
	return 0
}

func (x *GenerateQueueRequest) GetPatientName() string {
	if x != nil && x.PatientName != nil {
		return *x.PatientName
	}
	return ""
}

func (x *GenerateQueueRequest) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *GenerateQueueRequest) GetDoctorSpecialization() string {
	if x != nil {
		return x.DoctorSpecialization
	}
	return ""
}

func (x *GenerateQueueRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type QueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *Queue                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueResponse) Reset() {
	*x = QueueResponse{}
	mi := &file_queue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueResponse) ProtoMessage() {}

func (x *QueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueResponse.ProtoReflect.Descriptor instead.
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{6}
}

func (x *QueueResponse) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

type QueueListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []*Queue               `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueListResponse) Reset() {
	*x = QueueListResponse{}
	mi := &file_queue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueListResponse) ProtoMessage() {}

func (x *QueueListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueListResponse.ProtoReflect.Descriptor instead.
func (*QueueListResponse) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{7}
}

func (x *QueueListResponse) GetQueues() []*Queue {
	if x != nil {
		return x.Queues
	}
	return nil
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_queue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{8}
}

var File_queue_proto protoreflect.FileDescriptor

const file_queue_proto_rawDesc = "" +
	"\n" +
	"\vqueue.proto\x12\x05queue\"\x95\x04\n" +
	"\x05Queue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x1b\n" +
	"\tuser_role\x18\x04 \x01(\tR\buserRole\x12\"\n" +
	"\n" +
	"patient_id\x18\x05 \x01(\rH\x00R\tpatientId\x88\x01\x01\x12&\n" +
	"\fpatient_name\x18\x06 \x01(\tH\x01R\vpatientName\x88\x01\x01\x12\x1b\n" +
	"\tdoctor_id\x18\a \x01(\rR\bdoctorId\x12\x1f\n" +
	"\vdoctor_name\x18\b \x01(\tR\n" +
	"doctorName\x123\n" +
	"\x15doctor_specialization\x18\t \x01(\tR\x14doctorSpecialization\x12*\n" +
	"\x0eappointment_id\x18\n" +
	" \x01(\rH\x02R\rappointmentId\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\v \x01(\tR\x04type\x12!\n" +
	"\fqueue_number\x18\f \x01(\x05R\vqueueNumber\x12\x1d\n" +
	"\n" +
	"start_from\x18\r \x01(\tR\tstartFrom\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAtB\r\n" +
	"\v_patient_idB\x0f\n" +
	"\r_patient_nameB\x11\n" +
	"\x0f_appointment_id\" \n" +
	"\x0eQueueIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\".\n" +
	"\x0fDoctorIDRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\rR\bdoctorId\"8\n" +
	"\x12CreateQueueRequest\x12\"\n" +
	"\x05queue\x18\x01 \x01(\v2\f.queue.QueueR\x05queue\"8\n" +
	"\x12UpdateQueueRequest\x12\"\n" +
	"\x05queue\x18\x01 \x01(\v2\f.queue.QueueR\x05queue\"\x9b\x03\n" +
	"\x14GenerateQueueRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\rR\bdoctorId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x1b\n" +
	"\tuser_role\x18\x04 \x01(\tR\buserRole\x12*\n" +
	"\x0eappointment_id\x18\x05 \x01(\rH\x00R\rappointmentId\x88\x01\x01\x12\"\n" +
	"\n" +
	"patient_id\x18\x06 \x01(\rH\x01R\tpatientId\x88\x01\x01\x12&\n" +
	"\fpatient_name\x18\a \x01(\tH\x02R\vpatientName\x88\x01\x01\x12\x1f\n" +
	"\vdoctor_name\x18\b \x01(\tR\n" +
	"doctorName\x123\n" +
	"\x15doctor_specialization\x18\t \x01(\tR\x14doctorSpecialization\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04typeB\x11\n" +
	"\x0f_appointment_idB\r\n" +
	"\v_patient_idB\x0f\n" +
	"\r_patient_name\"3\n" +
	"\rQueueResponse\x12\"\n" +
	"\x05queue\x18\x01 \x01(\v2\f.queue.QueueR\x05queue\"9\n" +
	"\x11QueueListResponse\x12$\n" +
	"\x06queues\x18\x01 \x03(\v2\f.queue.QueueR\x06queues\"\x0f\n" +
	"\rEmptyResponse2\xdf\x02\n" +
	"\fQueueService\x12;\n" +
	"\fGetQueueByID\x12\x15.queue.QueueIDRequest\x1a\x14.queue.QueueResponse\x12J\n" +
	"\x16GetTodayQueuesByDoctor\x12\x16.queue.DoctorIDRequest\x1a\x18.queue.QueueListResponse\x12>\n" +
	"\vCreateQueue\x12\x19.queue.CreateQueueRequest\x1a\x14.queue.EmptyResponse\x12>\n" +
	"\vUpdateQueue\x12\x19.queue.UpdateQueueRequest\x1a\x14.queue.EmptyResponse\x12F\n" +
	"\x11GenerateNextQueue\x12\x1b.queue.GenerateQueueRequest\x1a\x14.queue.QueueResponseB\rZ\vqueue/pb;pbb\x06proto3"

var (
	file_queue_proto_rawDescOnce sync.Once
	file_queue_proto_rawDescData []byte
)

func file_queue_proto_rawDescGZIP() []byte {
	file_queue_proto_rawDescOnce.Do(func() {
		file_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_queue_proto_rawDesc), len(file_queue_proto_rawDesc)))
	})
	return file_queue_proto_rawDescData
}

var file_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_queue_proto_goTypes = []any{
	(*Queue)(nil),                // 0: queue.Queue
	(*QueueIDRequest)(nil),       // 1: queue.QueueIDRequest
	(*DoctorIDRequest)(nil),      // 2: queue.DoctorIDRequest
	(*CreateQueueRequest)(nil),   // 3: queue.CreateQueueRequest
	(*UpdateQueueRequest)(nil),   // 4: queue.UpdateQueueRequest
	(*GenerateQueueRequest)(nil), // 5: queue.GenerateQueueRequest
	(*QueueResponse)(nil),        // 6: queue.QueueResponse
	(*QueueListResponse)(nil),    // 7: queue.QueueListResponse
	(*EmptyResponse)(nil),        // 8: queue.EmptyResponse
}
var file_queue_proto_depIdxs = []int32{
	0, // 0: queue.CreateQueueRequest.queue:type_name -> queue.Queue
	0, // 1: queue.UpdateQueueRequest.queue:type_name -> queue.Queue
	0, // 2: queue.QueueResponse.queue:type_name -> queue.Queue
	0, // 3: queue.QueueListResponse.queues:type_name -> queue.Queue
	1, // 4: queue.QueueService.GetQueueByID:input_type -> queue.QueueIDRequest
	2, // 5: queue.QueueService.GetTodayQueuesByDoctor:input_type -> queue.DoctorIDRequest
	3, // 6: queue.QueueService.CreateQueue:input_type -> queue.CreateQueueRequest
	4, // 7: queue.QueueService.UpdateQueue:input_type -> queue.UpdateQueueRequest
	5, // 8: queue.QueueService.GenerateNextQueue:input_type -> queue.GenerateQueueRequest
	6, // 9: queue.QueueService.GetQueueByID:output_type -> queue.QueueResponse
	7, // 10: queue.QueueService.GetTodayQueuesByDoctor:output_type -> queue.QueueListResponse
	8, // 11: queue.QueueService.CreateQueue:output_type -> queue.EmptyResponse
	8, // 12: queue.QueueService.UpdateQueue:output_type -> queue.EmptyResponse
	6, // 13: queue.QueueService.GenerateNextQueue:output_type -> queue.QueueResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_queue_proto_init() }
func file_queue_proto_init() {
	if File_queue_proto != nil {
		return
	}
	file_queue_proto_msgTypes[0].OneofWrappers = []any{}
	file_queue_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_proto_rawDesc), len(file_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queue_proto_goTypes,
		DependencyIndexes: file_queue_proto_depIdxs,
		MessageInfos:      file_queue_proto_msgTypes,
	}.Build()
	File_queue_proto = out.File
	file_queue_proto_goTypes = nil
	file_queue_proto_depIdxs = nil
}
