// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/consultation/payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentLog struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId     string                  `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Response      *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"` // Use StringValue to allow nullability
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentLog) Reset() {
	*x = PaymentLog{}
	mi := &file_proto_consultation_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentLog) ProtoMessage() {}

func (x *PaymentLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentLog.ProtoReflect.Descriptor instead.
func (*PaymentLog) Descriptor() ([]byte, []int) {
	return file_proto_consultation_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentLog) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentLog) GetResponse() *wrapperspb.StringValue {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *PaymentLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentLog) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConsultationId string                 `protobuf:"bytes,1,opt,name=consultation_id,json=consultationId,proto3" json:"consultation_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Method         string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"` // e.g., "credit_card", "bank_transfer"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_proto_consultation_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_consultation_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentRequest) GetConsultationId() string {
	if x != nil {
		return x.ConsultationId
	}
	return ""
}

func (x *PaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type PaymentResponse struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Id               string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConsultationId   string                  `protobuf:"bytes,2,opt,name=consultation_id,json=consultationId,proto3" json:"consultation_id,omitempty"`
	ConsultationDate *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=consultation_date,json=consultationDate,proto3" json:"consultation_date,omitempty"`
	PatientId        string                  `protobuf:"bytes,4,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	PatientName      *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	DoctorId         string                  `protobuf:"bytes,6,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DoctorName       *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`
	Amount           float64                 `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Method           *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=method,proto3" json:"method,omitempty"`
	Gateway          *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=gateway,proto3" json:"gateway,omitempty"`
	PaymentLog       []*PaymentLog           `protobuf:"bytes,11,rep,name=payment_log,json=paymentLog,proto3" json:"payment_log,omitempty"`
	Status           *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	CreatedBy        *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedName      *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=created_name,json=createdName,proto3" json:"created_name,omitempty"`
	CreatedEmail     *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=created_email,json=createdEmail,proto3" json:"created_email,omitempty"`
	CreatedRole      *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=created_role,json=createdRole,proto3" json:"created_role,omitempty"`
	CreatedAt        *timestamppb.Timestamp  `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedBy        *wrapperspb.StringValue `protobuf:"bytes,18,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedName      *wrapperspb.StringValue `protobuf:"bytes,19,opt,name=updated_name,json=updatedName,proto3" json:"updated_name,omitempty"`
	UpdatedEmail     *wrapperspb.StringValue `protobuf:"bytes,20,opt,name=updated_email,json=updatedEmail,proto3" json:"updated_email,omitempty"`
	UpdatedRole      *wrapperspb.StringValue `protobuf:"bytes,21,opt,name=updated_role,json=updatedRole,proto3" json:"updated_role,omitempty"`
	UpdatedAt        *timestamppb.Timestamp  `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_proto_consultation_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_consultation_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentResponse) GetConsultationId() string {
	if x != nil {
		return x.ConsultationId
	}
	return ""
}

func (x *PaymentResponse) GetConsultationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ConsultationDate
	}
	return nil
}

func (x *PaymentResponse) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *PaymentResponse) GetPatientName() *wrapperspb.StringValue {
	if x != nil {
		return x.PatientName
	}
	return nil
}

func (x *PaymentResponse) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *PaymentResponse) GetDoctorName() *wrapperspb.StringValue {
	if x != nil {
		return x.DoctorName
	}
	return nil
}

func (x *PaymentResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentResponse) GetMethod() *wrapperspb.StringValue {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *PaymentResponse) GetGateway() *wrapperspb.StringValue {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *PaymentResponse) GetPaymentLog() []*PaymentLog {
	if x != nil {
		return x.PaymentLog
	}
	return nil
}

func (x *PaymentResponse) GetStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PaymentResponse) GetCreatedBy() *wrapperspb.StringValue {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *PaymentResponse) GetCreatedName() *wrapperspb.StringValue {
	if x != nil {
		return x.CreatedName
	}
	return nil
}

func (x *PaymentResponse) GetCreatedEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.CreatedEmail
	}
	return nil
}

func (x *PaymentResponse) GetCreatedRole() *wrapperspb.StringValue {
	if x != nil {
		return x.CreatedRole
	}
	return nil
}

func (x *PaymentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentResponse) GetUpdatedBy() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

func (x *PaymentResponse) GetUpdatedName() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedName
	}
	return nil
}

func (x *PaymentResponse) GetUpdatedEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedEmail
	}
	return nil
}

func (x *PaymentResponse) GetUpdatedRole() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedRole
	}
	return nil
}

func (x *PaymentResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PaymentUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // unique identifier for the payment
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"` // updated amount
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`   // updated status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentUpdateRequest) Reset() {
	*x = PaymentUpdateRequest{}
	mi := &file_proto_consultation_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentUpdateRequest) ProtoMessage() {}

func (x *PaymentUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentUpdateRequest.ProtoReflect.Descriptor instead.
func (*PaymentUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_consultation_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentUpdateRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentUpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Buatkan message untuk menangani webhook baik dari payment gateway atau pihak ketiga lainnya, sertakan id unik sebagai identifier id dari pihak ketiga
type PaymentWebhookRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // unique identifier for the webhook
	ExternalId    string                  `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // ID unik dari pihak ketiga
	PaymentId     string                  `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`    // ID pembayaran terkait
	EventType     string                  `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`    // Jenis event dari webhook, misalnya "payment_success", "payment_failed"
	Payload       *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                         // Payload JSON dari webhook
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentWebhookRequest) Reset() {
	*x = PaymentWebhookRequest{}
	mi := &file_proto_consultation_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentWebhookRequest) ProtoMessage() {}

func (x *PaymentWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentWebhookRequest.ProtoReflect.Descriptor instead.
func (*PaymentWebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_consultation_payment_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentWebhookRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *PaymentWebhookRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentWebhookRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PaymentWebhookRequest) GetPayload() *wrapperspb.StringValue {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_consultation_payment_proto protoreflect.FileDescriptor

const file_proto_consultation_payment_proto_rawDesc = "" +
	"\n" +
	" proto/consultation/payment.proto\x12\fconsultation\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xeb\x01\n" +
	"\n" +
	"PaymentLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x128\n" +
	"\bresponse\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\bresponse\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"i\n" +
	"\x0ePaymentRequest\x12'\n" +
	"\x0fconsultation_id\x18\x01 \x01(\tR\x0econsultationId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\"\xc0\t\n" +
	"\x0fPaymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconsultation_id\x18\x02 \x01(\tR\x0econsultationId\x12G\n" +
	"\x11consultation_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x10consultationDate\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x04 \x01(\tR\tpatientId\x12?\n" +
	"\fpatient_name\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\vpatientName\x12\x1b\n" +
	"\tdoctor_id\x18\x06 \x01(\tR\bdoctorId\x12=\n" +
	"\vdoctor_name\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"doctorName\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x124\n" +
	"\x06method\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\x06method\x126\n" +
	"\agateway\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\agateway\x129\n" +
	"\vpayment_log\x18\v \x03(\v2\x18.consultation.PaymentLogR\n" +
	"paymentLog\x124\n" +
	"\x06status\x18\f \x01(\v2\x1c.google.protobuf.StringValueR\x06status\x12;\n" +
	"\n" +
	"created_by\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\tcreatedBy\x12?\n" +
	"\fcreated_name\x18\x0e \x01(\v2\x1c.google.protobuf.StringValueR\vcreatedName\x12A\n" +
	"\rcreated_email\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueR\fcreatedEmail\x12?\n" +
	"\fcreated_role\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\vcreatedRole\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\n" +
	"updated_by\x18\x12 \x01(\v2\x1c.google.protobuf.StringValueR\tupdatedBy\x12?\n" +
	"\fupdated_name\x18\x13 \x01(\v2\x1c.google.protobuf.StringValueR\vupdatedName\x12A\n" +
	"\rupdated_email\x18\x14 \x01(\v2\x1c.google.protobuf.StringValueR\fupdatedEmail\x12?\n" +
	"\fupdated_role\x18\x15 \x01(\v2\x1c.google.protobuf.StringValueR\vupdatedRole\x129\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"V\n" +
	"\x14PaymentUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xbe\x01\n" +
	"\x15PaymentWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\tR\tpaymentId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x126\n" +
	"\apayload\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\apayload2\xec\x02\n" +
	"\x0ePaymentService\x12P\n" +
	"\x11CreatePaymentGRPC\x12\x1c.consultation.PaymentRequest\x1a\x1d.consultation.PaymentResponse\x12Q\n" +
	"\x12GetPaymentByIdGRPC\x12\x1c.google.protobuf.StringValue\x1a\x1d.consultation.PaymentResponse\x12V\n" +
	"\x11UpdatePaymentGRPC\x12\".consultation.PaymentUpdateRequest\x1a\x1d.consultation.PaymentResponse\x12]\n" +
	"\x18HandlePaymentWebhookGRPC\x12#.consultation.PaymentWebhookRequest\x1a\x1c.google.protobuf.StringValueB;Z9consultation-service/internal/payment/delivery/grpc/pb;pbb\x06proto3"

var (
	file_proto_consultation_payment_proto_rawDescOnce sync.Once
	file_proto_consultation_payment_proto_rawDescData []byte
)

func file_proto_consultation_payment_proto_rawDescGZIP() []byte {
	file_proto_consultation_payment_proto_rawDescOnce.Do(func() {
		file_proto_consultation_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_consultation_payment_proto_rawDesc), len(file_proto_consultation_payment_proto_rawDesc)))
	})
	return file_proto_consultation_payment_proto_rawDescData
}

var file_proto_consultation_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_consultation_payment_proto_goTypes = []any{
	(*PaymentLog)(nil),             // 0: consultation.PaymentLog
	(*PaymentRequest)(nil),         // 1: consultation.PaymentRequest
	(*PaymentResponse)(nil),        // 2: consultation.PaymentResponse
	(*PaymentUpdateRequest)(nil),   // 3: consultation.PaymentUpdateRequest
	(*PaymentWebhookRequest)(nil),  // 4: consultation.PaymentWebhookRequest
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_proto_consultation_payment_proto_depIdxs = []int32{
	5,  // 0: consultation.PaymentLog.response:type_name -> google.protobuf.StringValue
	6,  // 1: consultation.PaymentLog.created_at:type_name -> google.protobuf.Timestamp
	6,  // 2: consultation.PaymentLog.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 3: consultation.PaymentResponse.consultation_date:type_name -> google.protobuf.Timestamp
	5,  // 4: consultation.PaymentResponse.patient_name:type_name -> google.protobuf.StringValue
	5,  // 5: consultation.PaymentResponse.doctor_name:type_name -> google.protobuf.StringValue
	5,  // 6: consultation.PaymentResponse.method:type_name -> google.protobuf.StringValue
	5,  // 7: consultation.PaymentResponse.gateway:type_name -> google.protobuf.StringValue
	0,  // 8: consultation.PaymentResponse.payment_log:type_name -> consultation.PaymentLog
	5,  // 9: consultation.PaymentResponse.status:type_name -> google.protobuf.StringValue
	5,  // 10: consultation.PaymentResponse.created_by:type_name -> google.protobuf.StringValue
	5,  // 11: consultation.PaymentResponse.created_name:type_name -> google.protobuf.StringValue
	5,  // 12: consultation.PaymentResponse.created_email:type_name -> google.protobuf.StringValue
	5,  // 13: consultation.PaymentResponse.created_role:type_name -> google.protobuf.StringValue
	6,  // 14: consultation.PaymentResponse.created_at:type_name -> google.protobuf.Timestamp
	5,  // 15: consultation.PaymentResponse.updated_by:type_name -> google.protobuf.StringValue
	5,  // 16: consultation.PaymentResponse.updated_name:type_name -> google.protobuf.StringValue
	5,  // 17: consultation.PaymentResponse.updated_email:type_name -> google.protobuf.StringValue
	5,  // 18: consultation.PaymentResponse.updated_role:type_name -> google.protobuf.StringValue
	6,  // 19: consultation.PaymentResponse.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 20: consultation.PaymentWebhookRequest.payload:type_name -> google.protobuf.StringValue
	1,  // 21: consultation.PaymentService.CreatePaymentGRPC:input_type -> consultation.PaymentRequest
	5,  // 22: consultation.PaymentService.GetPaymentByIdGRPC:input_type -> google.protobuf.StringValue
	3,  // 23: consultation.PaymentService.UpdatePaymentGRPC:input_type -> consultation.PaymentUpdateRequest
	4,  // 24: consultation.PaymentService.HandlePaymentWebhookGRPC:input_type -> consultation.PaymentWebhookRequest
	2,  // 25: consultation.PaymentService.CreatePaymentGRPC:output_type -> consultation.PaymentResponse
	2,  // 26: consultation.PaymentService.GetPaymentByIdGRPC:output_type -> consultation.PaymentResponse
	2,  // 27: consultation.PaymentService.UpdatePaymentGRPC:output_type -> consultation.PaymentResponse
	5,  // 28: consultation.PaymentService.HandlePaymentWebhookGRPC:output_type -> google.protobuf.StringValue
	25, // [25:29] is the sub-list for method output_type
	21, // [21:25] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_consultation_payment_proto_init() }
func file_proto_consultation_payment_proto_init() {
	if File_proto_consultation_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_consultation_payment_proto_rawDesc), len(file_proto_consultation_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_consultation_payment_proto_goTypes,
		DependencyIndexes: file_proto_consultation_payment_proto_depIdxs,
		MessageInfos:      file_proto_consultation_payment_proto_msgTypes,
	}.Build()
	File_proto_consultation_payment_proto = out.File
	file_proto_consultation_payment_proto_goTypes = nil
	file_proto_consultation_payment_proto_depIdxs = nil
}
